-- Fonti RSS pubbliche di esempio, pronte da attivare. Verifica sempre i
-- termini d'uso di ogni fonte prima di un utilizzo in produzione.
insert into public.sources (name, rss_url, website_url, category) values
  -- Nota: "/feed" senza slash finale — con lo slash il sito risponde 403.
  ('Il Post', 'https://www.ilpost.it/feed', 'https://www.ilpost.it', 'Attualità'),
  ('ANSA - Homepage', 'https://www.ansa.it/sito/ansait_rss.xml', 'https://www.ansa.it', 'Attualità'),
  ('Il Fatto Quotidiano', 'https://www.ilfattoquotidiano.it/feed/', 'https://www.ilfattoquotidiano.it', 'Attualità'),
  ('Wired Italia', 'https://www.wired.it/feed/rss', 'https://www.wired.it', 'Tecnologia'),
  ('BBC News', 'http://feeds.bbci.co.uk/news/rss.xml', 'https://www.bbc.com/news', 'Attualità'),
  ('TechCrunch', 'https://techcrunch.com/feed/', 'https://techcrunch.com', 'Tecnologia'),
  ('The Verge', 'https://www.theverge.com/rss/index.xml', 'https://www.theverge.com', 'Tecnologia'),

  -- Fonti per categoria, mix italiano/internazionale (tutte verificate live:
  -- HTTP 200 + XML valido, prima dell'inserimento qui).
  ('ANSA - Politica', 'https://www.ansa.it/sito/notizie/politica/politica_rss.xml', 'https://www.ansa.it', 'Politica'),
  ('ANSA - Economia', 'https://www.ansa.it/sito/notizie/economia/economia_rss.xml', 'https://www.ansa.it', 'Economia'),
  ('ANSA - Sport', 'https://www.ansa.it/sito/notizie/sport/sport_rss.xml', 'https://www.ansa.it', 'Sport'),
  ('ANSA - Cultura', 'https://www.ansa.it/sito/notizie/cultura/cultura_rss.xml', 'https://www.ansa.it', 'Cultura'),
  ('ANSA - Mondo', 'https://www.ansa.it/sito/notizie/mondo/mondo_rss.xml', 'https://www.ansa.it', 'Mondo'),
  -- Nota: "ANSA - Tecnologia" esclusa dopo verifica: il feed risponde 200
  -- ma tutti gli articoli sono fermi a maggio 2023 (feed abbandonato).
  -- Tecnologia resta comunque coperta da Wired Italia, TechCrunch, The
  -- Verge, BBC Technology.
  ('Rai News - Esteri', 'https://www.rainews.it/rss/esteri', 'https://www.rainews.it', 'Mondo'),
  ('Rai News - Sport', 'https://www.rainews.it/rss/sport', 'https://www.rainews.it', 'Sport'),
  -- Nota: "Gazzetta dello Sport" (gazzetta.it/rss/home.xml) è stata esclusa
  -- dopo verifica: il feed risponde 200 ma contiene articoli del 2022-2023,
  -- non notizie correnti (lastBuildDate anch'esso fermo a gennaio 2024).
  ('BBC World', 'https://feeds.bbci.co.uk/news/world/rss.xml', 'https://www.bbc.com/news/world', 'Mondo'),
  ('BBC Business', 'https://feeds.bbci.co.uk/news/business/rss.xml', 'https://www.bbc.com/news/business', 'Economia'),
  ('BBC Technology', 'https://feeds.bbci.co.uk/news/technology/rss.xml', 'https://www.bbc.com/news/technology', 'Tecnologia'),
  ('BBC Sport', 'https://feeds.bbci.co.uk/sport/rss.xml?edition=uk', 'https://www.bbc.com/sport', 'Sport'),
  ('BBC Science', 'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml', 'https://www.bbc.com/news/science_and_environment', 'Scienza')
on conflict (rss_url) do nothing;

-- Tag di esempio per la pagina impostazioni. Nessuna logica automatica
-- assegna i tag agli articoli ingested in v1 (vedi README): l'associazione
-- article_tag è predisposta a schema ma va popolata manualmente finché non
-- si aggiunge un classificatore dedicato.
insert into public.tags (name) values
  ('Politica'), ('Tecnologia'), ('Economia'), ('Sport'), ('Cultura'), ('Scienza'), ('Mondo')
on conflict (name) do nothing;

-- Macro Step 2 (geo-tagging): dati di riferimento per `regions`. lat/lng
-- sono centroidi approssimativi (capoluogo/capitale), sufficienti per un
-- click-area sulla mappa dello Step 3, non per precisione cartografica.

-- Regioni italiane, complete (20).
insert into public.regions (name, level, lat, lng) values
  ('Abruzzo', 'region', 42.35, 13.40),
  ('Basilicata', 'region', 40.64, 15.80),
  ('Calabria', 'region', 38.91, 16.59),
  ('Campania', 'region', 40.85, 14.27),
  ('Emilia-Romagna', 'region', 44.49, 11.34),
  ('Friuli-Venezia Giulia', 'region', 45.65, 13.77),
  ('Lazio', 'region', 41.90, 12.50),
  ('Liguria', 'region', 44.41, 8.93),
  ('Lombardia', 'region', 45.46, 9.19),
  ('Marche', 'region', 43.62, 13.52),
  ('Molise', 'region', 41.56, 14.66),
  ('Piemonte', 'region', 45.07, 7.69),
  ('Puglia', 'region', 41.12, 16.87),
  ('Sardegna', 'region', 39.22, 9.12),
  ('Sicilia', 'region', 38.12, 13.36),
  ('Toscana', 'region', 43.77, 11.25),
  ('Trentino-Alto Adige', 'region', 46.07, 11.12),
  ('Umbria', 'region', 43.11, 12.39),
  ('Valle d''Aosta', 'region', 45.74, 7.32),
  ('Veneto', 'region', 45.44, 12.33)
on conflict (name, level) do nothing;

-- Macro-regioni: emerse ispezionando i path reali di ANSA - Mondo
-- (/mondo/europa/, /mondo/americalatina/, ...), sono l'unico segnale
-- geografico strutturato che l'URL pattern matching riesce a intercettare
-- su questo mix di fonti (vedi lib/geo-tagging/url-pattern.ts).
insert into public.regions (name, level, lat, lng) values
  ('Europa', 'macro_region', 50.0, 15.0),
  ('America Latina', 'macro_region', -15.0, -60.0),
  ('Nord America', 'macro_region', 45.0, -100.0),
  ('Asia', 'macro_region', 34.0, 100.0),
  ('Africa', 'macro_region', 2.0, 20.0),
  ('Medio Oriente', 'macro_region', 29.0, 45.0)
on conflict (name, level) do nothing;

-- Città/province italiane più citate nelle notizie: set curato (~50), non
-- le 107 province formali (molte non compaiono mai per nome nelle notizie
-- nazionali/internazionali — righe morte). Estendibile aggiungendo righe.
insert into public.regions (name, level, parent_id, lat, lng) values
  ('Roma', 'province', (select id from public.regions where name = 'Lazio' and level = 'region'), 41.90, 12.50),
  ('Milano', 'province', (select id from public.regions where name = 'Lombardia' and level = 'region'), 45.46, 9.19),
  ('Napoli', 'province', (select id from public.regions where name = 'Campania' and level = 'region'), 40.85, 14.27),
  ('Torino', 'province', (select id from public.regions where name = 'Piemonte' and level = 'region'), 45.07, 7.69),
  ('Palermo', 'province', (select id from public.regions where name = 'Sicilia' and level = 'region'), 38.12, 13.36),
  ('Genova', 'province', (select id from public.regions where name = 'Liguria' and level = 'region'), 44.41, 8.93),
  ('Bologna', 'province', (select id from public.regions where name = 'Emilia-Romagna' and level = 'region'), 44.49, 11.34),
  ('Firenze', 'province', (select id from public.regions where name = 'Toscana' and level = 'region'), 43.77, 11.25),
  ('Bari', 'province', (select id from public.regions where name = 'Puglia' and level = 'region'), 41.12, 16.87),
  ('Catania', 'province', (select id from public.regions where name = 'Sicilia' and level = 'region'), 37.50, 15.09),
  ('Venezia', 'province', (select id from public.regions where name = 'Veneto' and level = 'region'), 45.44, 12.33),
  ('Verona', 'province', (select id from public.regions where name = 'Veneto' and level = 'region'), 45.44, 10.99),
  ('Messina', 'province', (select id from public.regions where name = 'Sicilia' and level = 'region'), 38.19, 15.55),
  ('Padova', 'province', (select id from public.regions where name = 'Veneto' and level = 'region'), 45.41, 11.88),
  ('Trieste', 'province', (select id from public.regions where name = 'Friuli-Venezia Giulia' and level = 'region'), 45.65, 13.77),
  ('Brescia', 'province', (select id from public.regions where name = 'Lombardia' and level = 'region'), 45.54, 10.22),
  ('Taranto', 'province', (select id from public.regions where name = 'Puglia' and level = 'region'), 40.47, 17.24),
  ('Prato', 'province', (select id from public.regions where name = 'Toscana' and level = 'region'), 43.88, 11.10),
  ('Reggio Calabria', 'province', (select id from public.regions where name = 'Calabria' and level = 'region'), 38.11, 15.65),
  ('Reggio Emilia', 'province', (select id from public.regions where name = 'Emilia-Romagna' and level = 'region'), 44.70, 10.63),
  ('Modena', 'province', (select id from public.regions where name = 'Emilia-Romagna' and level = 'region'), 44.65, 10.93),
  ('Perugia', 'province', (select id from public.regions where name = 'Umbria' and level = 'region'), 43.11, 12.39),
  ('Ravenna', 'province', (select id from public.regions where name = 'Emilia-Romagna' and level = 'region'), 44.42, 12.20),
  ('Livorno', 'province', (select id from public.regions where name = 'Toscana' and level = 'region'), 43.55, 10.31),
  ('Cagliari', 'province', (select id from public.regions where name = 'Sardegna' and level = 'region'), 39.22, 9.12),
  ('Foggia', 'province', (select id from public.regions where name = 'Puglia' and level = 'region'), 41.46, 15.55),
  ('Rimini', 'province', (select id from public.regions where name = 'Emilia-Romagna' and level = 'region'), 44.06, 12.57),
  ('Salerno', 'province', (select id from public.regions where name = 'Campania' and level = 'region'), 40.68, 14.77),
  ('Ferrara', 'province', (select id from public.regions where name = 'Emilia-Romagna' and level = 'region'), 44.84, 11.62),
  ('Sassari', 'province', (select id from public.regions where name = 'Sardegna' and level = 'region'), 40.73, 8.56),
  ('Latina', 'province', (select id from public.regions where name = 'Lazio' and level = 'region'), 41.47, 12.90),
  ('Monza', 'province', (select id from public.regions where name = 'Lombardia' and level = 'region'), 45.58, 9.27),
  ('Siracusa', 'province', (select id from public.regions where name = 'Sicilia' and level = 'region'), 37.07, 15.29),
  ('Pescara', 'province', (select id from public.regions where name = 'Abruzzo' and level = 'region'), 42.46, 14.21),
  ('Bergamo', 'province', (select id from public.regions where name = 'Lombardia' and level = 'region'), 45.70, 9.67),
  ('Trento', 'province', (select id from public.regions where name = 'Trentino-Alto Adige' and level = 'region'), 46.07, 11.12),
  ('Vicenza', 'province', (select id from public.regions where name = 'Veneto' and level = 'region'), 45.55, 11.55),
  ('Terni', 'province', (select id from public.regions where name = 'Umbria' and level = 'region'), 42.56, 12.64),
  ('Bolzano', 'province', (select id from public.regions where name = 'Trentino-Alto Adige' and level = 'region'), 46.50, 11.35),
  ('Novara', 'province', (select id from public.regions where name = 'Piemonte' and level = 'region'), 45.45, 8.62),
  ('Piacenza', 'province', (select id from public.regions where name = 'Emilia-Romagna' and level = 'region'), 45.05, 9.69),
  ('Ancona', 'province', (select id from public.regions where name = 'Marche' and level = 'region'), 43.62, 13.52),
  ('Andria', 'province', (select id from public.regions where name = 'Puglia' and level = 'region'), 41.23, 16.30),
  ('Udine', 'province', (select id from public.regions where name = 'Friuli-Venezia Giulia' and level = 'region'), 46.06, 13.24),
  ('Arezzo', 'province', (select id from public.regions where name = 'Toscana' and level = 'region'), 43.46, 11.88),
  ('Lecce', 'province', (select id from public.regions where name = 'Puglia' and level = 'region'), 40.35, 18.17),
  ('La Spezia', 'province', (select id from public.regions where name = 'Liguria' and level = 'region'), 44.10, 9.82),
  ('Pisa', 'province', (select id from public.regions where name = 'Toscana' and level = 'region'), 43.72, 10.40),
  ('Como', 'province', (select id from public.regions where name = 'Lombardia' and level = 'region'), 45.81, 9.09),
  ('L''Aquila', 'province', (select id from public.regions where name = 'Abruzzo' and level = 'region'), 42.35, 13.40)
on conflict (name, level) do nothing;

-- Paesi: lista ampia dei più rilevanti per le notizie internazionali (non
-- tutti i ~195 stati membri ONU, stesso criterio delle province sopra).
insert into public.regions (name, level, lat, lng) values
  ('Italia', 'country', 41.90, 12.50),
  ('Francia', 'country', 48.86, 2.35),
  ('Germania', 'country', 52.52, 13.40),
  ('Spagna', 'country', 40.42, -3.70),
  ('Regno Unito', 'country', 51.51, -0.13),
  ('Portogallo', 'country', 38.72, -9.14),
  ('Paesi Bassi', 'country', 52.37, 4.90),
  ('Belgio', 'country', 50.85, 4.35),
  ('Svizzera', 'country', 46.95, 7.45),
  ('Austria', 'country', 48.21, 16.37),
  ('Grecia', 'country', 37.98, 23.73),
  ('Polonia', 'country', 52.23, 21.01),
  ('Repubblica Ceca', 'country', 50.09, 14.42),
  ('Slovacchia', 'country', 48.15, 17.11),
  ('Ungheria', 'country', 47.50, 19.04),
  ('Romania', 'country', 44.43, 26.10),
  ('Bulgaria', 'country', 42.70, 23.32),
  ('Croazia', 'country', 45.81, 15.98),
  ('Slovenia', 'country', 46.06, 14.51),
  ('Serbia', 'country', 44.79, 20.45),
  ('Bosnia ed Erzegovina', 'country', 43.86, 18.41),
  ('Albania', 'country', 41.33, 19.82),
  ('Macedonia del Nord', 'country', 41.99, 21.43),
  ('Montenegro', 'country', 42.44, 19.26),
  ('Kosovo', 'country', 42.67, 21.17),
  ('Danimarca', 'country', 55.68, 12.57),
  ('Svezia', 'country', 59.33, 18.06),
  ('Norvegia', 'country', 59.91, 10.75),
  ('Finlandia', 'country', 60.17, 24.94),
  ('Islanda', 'country', 64.15, -21.94),
  ('Irlanda', 'country', 53.35, -6.26),
  ('Lussemburgo', 'country', 49.61, 6.13),
  ('Malta', 'country', 35.90, 14.51),
  ('Cipro', 'country', 35.19, 33.38),
  ('Estonia', 'country', 59.44, 24.75),
  ('Lettonia', 'country', 56.95, 24.11),
  ('Lituania', 'country', 54.69, 25.28),
  ('Ucraina', 'country', 50.45, 30.52),
  ('Bielorussia', 'country', 53.90, 27.57),
  ('Moldova', 'country', 47.01, 28.86),
  ('Russia', 'country', 55.75, 37.62),
  ('Turchia', 'country', 39.93, 32.86),
  ('Vaticano', 'country', 41.90, 12.45),
  ('San Marino', 'country', 43.94, 12.45),
  ('Stati Uniti', 'country', 38.90, -77.04),
  ('Canada', 'country', 45.42, -75.70),
  ('Messico', 'country', 19.43, -99.13),
  ('Cuba', 'country', 23.13, -82.38),
  ('Haiti', 'country', 18.59, -72.31),
  ('Repubblica Dominicana', 'country', 18.49, -69.93),
  ('Guatemala', 'country', 14.63, -90.51),
  ('Honduras', 'country', 14.07, -87.19),
  ('El Salvador', 'country', 13.69, -89.19),
  ('Nicaragua', 'country', 12.11, -86.24),
  ('Costa Rica', 'country', 9.93, -84.08),
  ('Panama', 'country', 8.99, -79.52),
  ('Giamaica', 'country', 18.02, -76.80),
  ('Brasile', 'country', -15.79, -47.88),
  ('Argentina', 'country', -34.60, -58.38),
  ('Cile', 'country', -33.45, -70.65),
  ('Colombia', 'country', 4.71, -74.07),
  ('Perù', 'country', -12.05, -77.04),
  ('Venezuela', 'country', 10.49, -66.88),
  ('Ecuador', 'country', -0.19, -78.47),
  ('Bolivia', 'country', -16.50, -68.15),
  ('Paraguay', 'country', -25.30, -57.64),
  ('Uruguay', 'country', -34.90, -56.16),
  ('Cina', 'country', 39.90, 116.41),
  ('Giappone', 'country', 35.68, 139.65),
  ('Corea del Sud', 'country', 37.57, 126.98),
  ('Corea del Nord', 'country', 39.02, 125.75),
  ('India', 'country', 28.61, 77.21),
  ('Pakistan', 'country', 33.68, 73.05),
  ('Bangladesh', 'country', 23.81, 90.41),
  ('Afghanistan', 'country', 34.53, 69.17),
  ('Iran', 'country', 35.69, 51.39),
  ('Iraq', 'country', 33.31, 44.36),
  ('Arabia Saudita', 'country', 24.71, 46.68),
  ('Emirati Arabi Uniti', 'country', 24.47, 54.37),
  ('Qatar', 'country', 25.29, 51.53),
  ('Israele', 'country', 31.77, 35.21),
  ('Palestina', 'country', 31.90, 35.20),
  ('Siria', 'country', 33.51, 36.28),
  ('Libano', 'country', 33.89, 35.50),
  ('Giordania', 'country', 31.95, 35.93),
  ('Yemen', 'country', 15.37, 44.19),
  ('Kuwait', 'country', 29.38, 47.98),
  ('Kazakhistan', 'country', 51.17, 71.45),
  ('Uzbekistan', 'country', 41.30, 69.24),
  ('Indonesia', 'country', -6.21, 106.85),
  ('Malesia', 'country', 3.14, 101.69),
  ('Filippine', 'country', 14.60, 120.98),
  ('Thailandia', 'country', 13.76, 100.50),
  ('Vietnam', 'country', 21.03, 105.85),
  ('Myanmar', 'country', 19.75, 96.13),
  ('Cambogia', 'country', 11.56, 104.92),
  ('Singapore', 'country', 1.35, 103.82),
  ('Taiwan', 'country', 25.03, 121.57),
  ('Sri Lanka', 'country', 6.93, 79.85),
  ('Nepal', 'country', 27.72, 85.32),
  ('Mongolia', 'country', 47.92, 106.92),
  ('Egitto', 'country', 30.04, 31.24),
  ('Libia', 'country', 32.89, 13.19),
  ('Tunisia', 'country', 36.81, 10.18),
  ('Algeria', 'country', 36.75, 3.06),
  ('Marocco', 'country', 34.02, -6.83),
  ('Sudan', 'country', 15.50, 32.56),
  ('Etiopia', 'country', 9.03, 38.74),
  ('Somalia', 'country', 2.05, 45.32),
  ('Kenya', 'country', -1.29, 36.82),
  ('Nigeria', 'country', 9.08, 7.40),
  ('Ghana', 'country', 5.60, -0.19),
  ('Sudafrica', 'country', -25.75, 28.19),
  ('Repubblica Democratica del Congo', 'country', -4.32, 15.31),
  ('Costa d''Avorio', 'country', 6.83, -5.29),
  ('Senegal', 'country', 14.72, -17.47),
  ('Mali', 'country', 12.65, -8.00),
  ('Niger', 'country', 13.51, 2.11),
  ('Ciad', 'country', 12.13, 15.06),
  ('Camerun', 'country', 3.85, 11.50),
  ('Uganda', 'country', 0.35, 32.58),
  ('Tanzania', 'country', -6.16, 35.75),
  ('Zimbabwe', 'country', -17.83, 31.05),
  ('Mozambico', 'country', -25.97, 32.57),
  ('Ruanda', 'country', -1.94, 30.06),
  ('Australia', 'country', -35.28, 149.13),
  ('Nuova Zelanda', 'country', -41.29, 174.78),
  ('Papua Nuova Guinea', 'country', -9.48, 147.15),
  ('Fiji', 'country', -18.14, 178.44)
on conflict (name, level) do nothing;
